# Generated by Django 5.2 on 2025-05-15 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], default='pix', max_length=30)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_cliente', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.OneToOneField(error_messages={'unique': 'Já existe um pagamento registrado para este contrato.'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='contratos.contrato')),
            ],
        ),
    ]
