# Generated by Django 5.1.7 on 2025-08-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_transacao',
            field=models.CharField(blank=True, help_text='Código gerado pelo provedor de pagamento (se aplicável).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], default='pix', help_text='Escolha entre PIX, Boleto, Crédito ou Débito.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o pagamento.', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='O valor deve ser exatamente igual ao definido no contrato.', max_digits=10),
        ),
    ]
