# Generated by Django 5.1.7 on 2025-10-03 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_pagamento_codigo_transacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='ID do PaymentIntent gerado pelo Stripe.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_transacao',
            field=models.CharField(blank=True, help_text='Código adicional ou referência de transação (ex.: PIX QR Code, Boleto ID).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('card', 'Cartão de Crédito/Débito')], default='pix', help_text='Escolha entre PIX, Boleto ou Cartão.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em Processamento'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20),
        ),
    ]
