# Generated by Django 5.1.7 on 2025-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_remove_pagamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
