# Generated by Django 5.1.7 on 2025-10-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pagamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento gerado pelo Mercado Pago.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_transacao',
            field=models.CharField(blank=True, help_text='Código adicional ou referência de transação (ex.: PIX QR Code, Boleto URL).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='[DEPRECATED] ID do PaymentIntent do Stripe (manter temporariamente).', max_length=255, null=True),
        ),
    ]
