# Generated by Django 5.1.7 on 2025-10-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_pagamento_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='codigo_transacao',
            field=models.CharField(blank=True, help_text='Código/URL legado (ex.: QR Code PIX, link de boleto).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('checkout_pro', 'Checkout Pro')], default='checkout_pro', help_text='Pagamento via Mercado Pago (Checkout Pro).', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='[DEPRECATED] ID do PaymentIntent do Stripe.', max_length=255, null=True),
        ),
    ]
