# Generated by Django 5.1.7 on 2025-10-28 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_migrate_metodo_to_checkout_pro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='contratante',
            field=models.ForeignKey(default=1, help_text='Usuário que contratou e efetuará o pagamento.', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_contratante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
