# Generated by Django 5.2 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_estimado', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
