# Generated by Django 5.1.7 on 2025-09-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
    ]
