# Generated by Django 5.1.7 on 2025-11-06 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0003_alter_proposta_options'),
        ('trabalhos', '0007_rename_cliente_trabalho_contratante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='motivo_revisao',
            field=models.TextField(blank=True, default='', help_text='Explique o que mudou nesta nova proposta (valor/escopo/prazo).'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='numero_envio',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = proposta original; 2/3 = reenvios.'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='revisao_de',
            field=models.ForeignKey(blank=True, help_text='Referência para a proposta anterior quando esta é uma revisão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes', to='propostas.proposta'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='proposta',
            index=models.Index(fields=['trabalho', 'freelancer'], name='propostas_p_trabalh_3706aa_idx'),
        ),
        migrations.AddIndex(
            model_name='proposta',
            index=models.Index(fields=['freelancer', 'status'], name='propostas_p_freelan_da0ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='proposta',
            index=models.Index(fields=['trabalho', 'status'], name='propostas_p_trabalh_f1a8f4_idx'),
        ),
    ]
