# Generated by Django 5.1.7 on 2025-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_proposta_motivo_revisao_proposta_numero_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='motivo_recusa',
            field=models.TextField(blank=True, default='', help_text='Motivo pelo qual o contratante recusou esta proposta.'),
        ),
    ]
