# Generated by Django 5.2 on 2025-05-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='editada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(max_length=2000),
        ),
    ]
