# Generated by Django 5.1.7 on 2025-08-08 23:30

import django.db.models.deletion
import mensagens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
        ('mensagens', '0003_mensagem_editada_em_alter_mensagem_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_envio']},
        ),
        migrations.AddField(
            model_name='mensagem',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=mensagens.models.mensagem_upload_to),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='lido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['destinatario', 'lido'], name='mensagens_m_destina_6441c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['contrato', 'data_envio'], name='mensagens_m_contrat_703af7_idx'),
        ),
    ]
