# Generated by Django 5.1.7 on 2025-08-09 15:46

import django.db.models.deletion
import mensagens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
        ('mensagens', '0005_alter_mensagem_destinatario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='lido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='anexo',
            field=models.FileField(blank=True, help_text='Anexo opcional (imagens/PDF).', null=True, upload_to=mensagens.models.mensagem_upload_to),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='contrato',
            field=models.ForeignKey(help_text='Contrato ao qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(help_text='Usuário destinatário da mensagem.', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(help_text='Usuário que enviou a mensagem.', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(help_text='Conteúdo de texto da mensagem (máx. 2000 caracteres).', max_length=2000),
        ),
    ]
