# Generated by Django 5.1.7 on 2025-08-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0006_mensagem_lido_em_alter_mensagem_anexo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mensagem',
            name='mensagens_m_destina_6441c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='mensagem',
            name='mensagens_m_contrat_703af7_idx',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='lido',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='lido_em',
        ),
    ]
