# Generated by Django 5.1.7 on 2025-08-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0007_remove_mensagem_mensagens_m_destina_6441c4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='excluida',
            field=models.BooleanField(default=False, help_text='Indica se a mensagem foi excluída.'),
        ),
    ]
