# Generated by Django 5.1.7 on 2025-12-01 19:28

import freelancer.storage
import mensagens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0008_mensagem_excluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='anexo',
            field=models.FileField(blank=True, help_text='Anexo opcional (ZIP, RAR, DOCX, XLSX, imagens, PDF e outros).', null=True, storage=freelancer.storage.MensagensRawStorage(), upload_to=mensagens.models.mensagem_upload_to),
        ),
    ]
