# Generated by Django 5.1.7 on 2025-11-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ramo (único). Ex.: Backend, Frontend, Mobile, UI/UX, Data/IA, DevOps...', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='habilidade',
            options={'ordering': ['nome'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
