# Generated by Django 5.2 on 2025-05-20 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
        ('contratos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='freelancer',
            new_name='avaliado',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='cliente',
            new_name='avaliador',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='contratos.contrato'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('contrato', 'avaliador')},
        ),
    ]
