# Generated by Django 5.2 on 2025-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_cnpj_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nota_media',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
