# Generated by Django 5.2 on 2025-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_nota_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificacao_email',
            field=models.BooleanField(default=True),
        ),
    ]
