# Generated by Django 5.1.7 on 2025-11-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_foto_perfil_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sou_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
