# Generated by Django 5.1.7 on 2025-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_sou_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('foco', 'Modo Foco'), ('desativado', 'Desativado')], db_index=True, default='ativo', max_length=12),
        ),
    ]
