# Generated by Django 5.1.7 on 2025-11-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='status',
        ),
        migrations.AddField(
            model_name='usuario',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Momento em que o usuário desativou a conta.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deactivated_reason',
            field=models.TextField(blank=True, help_text='Motivo opcional informado pelo usuário ao desativar.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_suspended_self',
            field=models.BooleanField(db_index=True, default=False, help_text='Se verdadeiro, o usuário está em modo leitura (sem criar/editar ações).'),
        ),
    ]
