# Generated by Django 5.1.7 on 2025-11-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_status_usuario_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banido',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, o usuário está banido permanentemente.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banido_em',
            field=models.DateTimeField(blank=True, help_text='Data do banimento.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_suspended_admin',
            field=models.BooleanField(default=False, help_text='Usuário suspenso temporariamente por administrador.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_banimento',
            field=models.TextField(blank=True, help_text='Motivo do banimento aplicado pelo admin.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_suspensao_admin',
            field=models.TextField(blank=True, help_text='Motivo da suspensão aplicada pelo admin.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='suspenso_ate',
            field=models.DateTimeField(blank=True, help_text='Data em que a suspensão expira.', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='deactivated_reason',
            field=models.TextField(blank=True, help_text='Motivo informado pelo usuário ao desativar.', null=True),
        ),
    ]
