# Generated by Django 5.2 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alvo_id', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('usuario', 'Usuário'), ('trabalho', 'Trabalho'), ('proposta', 'Proposta'), ('mensagem', 'Mensagem'), ('outro', 'Outro')], max_length=20)),
                ('motivo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
