# Generated by Django 5.2 on 2025-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resposta_admin',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvida', 'Resolvida'), ('indeferida', 'Indeferida')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.TextField(max_length=500),
        ),
    ]
