# Generated by Django 5.1.7 on 2025-08-06 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_denuncia_resposta_admin_denuncia_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='data_envio',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='autor',
            new_name='denunciante',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='alvo_id',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='denunciado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='resposta_admin',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('analisando', 'Analisando'), ('resolvida', 'Resolvida')], default='pendente', max_length=20),
        ),
    ]
