# Generated by Django 5.1.7 on 2025-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_rename_data_envio_denuncia_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='resposta_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Analisando', 'Analisando'), ('Resolvida', 'Resolvida')], default='Pendente', max_length=20),
        ),
    ]
