# Generated by Django 5.1.7 on 2025-08-14 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
        ('denuncias', '0005_alter_denuncia_resposta_admin_alter_denuncia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='contratos.contrato'),
        ),
    ]
