# Generated by Django 5.1.7 on 2025-08-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0006_denuncia_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='contrato',
        ),
    ]
