# Generated by Django 5.1.7 on 2025-09-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_remove_denuncia_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='prova',
            field=models.ImageField(blank=True, help_text='Print ou evidência obrigatória para análise', null=True, upload_to='provas_denuncias/'),
        ),
    ]
