# Generated by Django 5.1.7 on 2025-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_denuncia_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='prova',
        ),
        migrations.CreateModel(
            name='DenunciaProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='provas_denuncias/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='denuncias.denuncia')),
            ],
        ),
    ]
