# Generated by Django 5.1.7 on 2025-11-30 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0009_remove_denuncia_prova_denunciaprova'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('advertencia', 'Advertência'), ('suspensao', 'Suspensão Temporária'), ('banimento', 'Banimento Permanente')], max_length=20)),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punicoes_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('denuncia_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punicoes', to='denuncias.denuncia')),
                ('usuario_punido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punicoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
