# Generated by Django 5.2 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('design', 'Design'), ('programacao', 'Programação'), ('escrita', 'Escrita'), ('traducao', 'Tradução'), ('marketing', 'Marketing')], max_length=100)),
                ('prazo', models.DateField()),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
            ],
        ),
    ]
