# Generated by Django 5.2 on 2025-05-11 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='categoria',
            field=models.CharField(choices=[('design_grafico', 'Design Gráfico'), ('desenvolvimento_web', 'Desenvolvimento Web'), ('desenvolvimento_mobile', 'Desenvolvimento Mobile'), ('ux_ui', 'UX/UI Design'), ('marketing_digital', 'Marketing Digital'), ('seo', 'SEO e Otimização'), ('automacao', 'Automação de Processos'), ('data_science', 'Ciência de Dados'), ('inteligencia_artificial', 'Inteligência Artificial'), ('infraestrutura', 'Infraestrutura e Redes'), ('seguranca', 'Segurança da Informação'), ('suporte_ti', 'Suporte Técnico'), ('audio_video', 'Produção Áudio/Visual'), ('erp_crm', 'Sistemas ERP/CRM'), ('qa_testes', 'Testes e Garantia de Qualidade')], max_length=100),
        ),
    ]
