# Generated by Django 5.2 on 2025-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0001_initial'),
        ('trabalhos', '0003_trabalho_atualizado_em_trabalho_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='categoria',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='trabalhos', to='habilidades.habilidade'),
        ),
    ]
