# Generated by Django 5.2 on 2025-05-28 22:26

import trabalhos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0004_remove_trabalho_categoria_trabalho_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=trabalhos.models.upload_to_anexos),
        ),
    ]
