# Generated by Django 5.1.7 on 2025-08-28 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0005_alter_trabalho_anexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos_direcionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='is_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('aguardando_aceitacao', 'Aguardando aceitação do freelancer'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('recusado', 'Recusado')], default='aberto', max_length=25),
        ),
    ]
