# Generated by Django 5.1.7 on 2025-10-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0006_trabalho_freelancer_trabalho_is_privado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalho',
            old_name='cliente',
            new_name='contratante',
        ),
    ]
