# Generated by Django 5.1.7 on 2025-11-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidades', '0002_ramo_alter_habilidade_options'),
        ('trabalhos', '0007_rename_cliente_trabalho_contratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='ramo',
            field=models.ForeignKey(blank=True, help_text='Macro-área do trabalho (ex.: Backend, Frontend, Mobile...). Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='habilidades.ramo'),
        ),
    ]
