# Generated by Django 5.2 on 2025-05-09 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('propostas', '0001_initial'),
        ('trabalhos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='propostas.proposta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='trabalhos.trabalho'),
        ),
    ]
