# Generated by Django 5.1.7 on 2025-08-29 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_valor'),
        ('propostas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='proposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='propostas.proposta'),
        ),
    ]
