# Generated by Django 5.1.7 on 2025-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
