# Generated by Django 5.1.7 on 2025-10-28 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contrato_options_remove_contrato_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='contratante',
            field=models.ForeignKey(default=1, help_text='Usuário contratante (quem publicou o trabalho).', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_contratante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='freelancer',
            field=models.ForeignKey(help_text='Usuário freelancer (quem realiza o trabalho).', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
